# Nithilan Kumaran - Personal Portfolio
title: "Nithilan Kumaran"
description: "Software Engineer & Game Developer"
email: nithilan.p.kumaran@gmail.com
baseurl: ""
url: "https://yourusername.github.io"

# Social Links
github_username: sathariels
linkedin_username: nithilan-kumaran
medium_username: Sathariels

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
